import eslintConfigPrettier from "eslint-config-prettier";
import { defineConfig } from "eslint/config";
import globals from "globals";

import importPlugin from "eslint-plugin-import";
import jsdoc from "eslint-plugin-jsdoc";
import sonarjs from "eslint-plugin-sonarjs";
import unusedImports from "eslint-plugin-unused-imports";
import tseslint from "typescript-eslint";

const jsdocRules = {
  "jsdoc/check-access": "warn",
  "jsdoc/check-alignment": "warn",
  "jsdoc/check-indentation": "warn",
  "jsdoc/check-line-alignment": "warn",
  "jsdoc/check-param-names": "warn",
  "jsdoc/check-property-names": "warn",
  "jsdoc/check-syntax": "warn",
  "jsdoc/check-tag-names": "warn",
  "jsdoc/check-template-names": "warn",
  "jsdoc/check-types": "warn",
  "jsdoc/check-values": "warn",
  "jsdoc/convert-to-jsdoc-comments": "warn",
  "jsdoc/empty-tags": "warn",
  "jsdoc/escape-inline-tags": "warn",
  "jsdoc/implements-on-classes": "warn",
  "jsdoc/imports-as-dependencies": "warn",
  "jsdoc/informative-docs": "warn",
  "jsdoc/lines-before-block": "warn",
  "jsdoc/match-description": "warn",
  "jsdoc/match-name": "warn",
  "jsdoc/multiline-blocks": "warn",
  "jsdoc/no-bad-blocks": "warn",
  "jsdoc/no-blank-block-descriptions": "warn",
  "jsdoc/no-defaults": "warn",
  "jsdoc/no-missing-syntax": "warn",
  "jsdoc/no-multi-asterisks": "warn",
  "jsdoc/no-restricted-syntax": "warn",
  "jsdoc/no-types": "warn",
  "jsdoc/no-undefined-types": "warn",
  "jsdoc/reject-any-type": "warn",
  "jsdoc/reject-function-type": "warn",
  "jsdoc/require-asterisk-prefix": "warn",
  "jsdoc/require-description": "warn",
  "jsdoc/require-description-complete-sentence": "warn",
  "jsdoc/require-example": "warn",
  "jsdoc/require-file-overview": "warn",
  "jsdoc/require-hyphen-before-param-description": "warn",
  "jsdoc/require-jsdoc": "warn",
  "jsdoc/require-next-description": "warn",
  "jsdoc/require-next-type": "warn",
  "jsdoc/require-param-description": "warn",
  "jsdoc/require-param-name": "warn",
  "jsdoc/require-param-type": "warn",
  "jsdoc/require-param": "warn",
  "jsdoc/require-property-description": "warn",
  "jsdoc/require-property-name": "warn",
  "jsdoc/require-property-type": "warn",
  "jsdoc/require-property": "warn",
  "jsdoc/require-rejects": "warn",
  "jsdoc/require-returns-check": "warn",
  "jsdoc/require-returns-description": "warn",
  "jsdoc/require-returns-type": "warn",
  "jsdoc/require-returns": "warn",
  "jsdoc/require-template": "warn",
  "jsdoc/require-template-description": "warn",
  "jsdoc/require-throws": "warn",
  "jsdoc/require-throws-description": "warn",
  "jsdoc/require-throws-type": "warn",
  "jsdoc/require-yields-check": "warn",
  "jsdoc/require-yields-description": "warn",
  "jsdoc/require-yields-type": "warn",
  "jsdoc/require-yields": "warn",
  "jsdoc/sort-tags": "warn",
  "jsdoc/tag-lines": "warn",
  "jsdoc/text-escaping": "warn",
  "jsdoc/ts-method-signature-style": "warn",
  "jsdoc/ts-prefer-function-type": "warn",
  "jsdoc/ts-no-unnecessary-template-expression": "warn",
  "jsdoc/type-formatting": "warn",
  "jsdoc/valid-types": "warn"
};

const typescriptEslintRules = {
  "@typescript-eslint/no-floating-promises": "error",
  "@typescript-eslint/no-misused-promises": "error",
  "@typescript-eslint/no-misused-new": "error",
  "@typescript-eslint/await-thenable": "error",
  "@typescript-eslint/no-for-in-array": "error",
  "@typescript-eslint/no-implied-eval": "error",
  "@typescript-eslint/no-unsafe-argument": "error",
  "@typescript-eslint/no-unsafe-assignment": "error",
  "@typescript-eslint/no-unsafe-call": "error",
  "@typescript-eslint/no-unsafe-member-access": "error",
  "@typescript-eslint/no-unsafe-return": "error",
  "@typescript-eslint/no-unsafe-declaration-merging": "error",
  "@typescript-eslint/no-unsafe-enum-comparison": "error",
  "@typescript-eslint/no-unsafe-unary-minus": "error",
  "@typescript-eslint/no-array-delete": "error",
  "@typescript-eslint/no-loss-of-precision": "error",
  "@typescript-eslint/no-dupe-class-members": "error",
  "@typescript-eslint/no-duplicate-enum-values": "error",
  "@typescript-eslint/no-redeclare": "error",
  "@typescript-eslint/no-invalid-void-type": "error",
  "@typescript-eslint/no-misused-spread": "error",
  "@typescript-eslint/unbound-method": "error",
  "@typescript-eslint/only-throw-error": [
    "error",
    {
      allow: [{ from: "file", name: "Error" }]
    }
  ],
  "@typescript-eslint/use-unknown-in-catch-callback-variable": "error",
  "@typescript-eslint/no-base-to-string": "error",
  "@typescript-eslint/restrict-plus-operands": "error",
  "@typescript-eslint/restrict-template-expressions": "error",
  "@typescript-eslint/return-await": "error",
  "@typescript-eslint/require-array-sort-compare": "error",
  "@typescript-eslint/no-explicit-any": "error",
  "@typescript-eslint/no-non-null-assertion": "error",
  "@typescript-eslint/no-non-null-asserted-optional-chain": "error",
  "@typescript-eslint/no-non-null-asserted-nullish-coalescing": "error",
  "@typescript-eslint/no-extra-non-null-assertion": "error",
  "@typescript-eslint/no-unnecessary-type-assertion": "error",
  "@typescript-eslint/strict-boolean-expressions": "warn",
  "@typescript-eslint/no-unnecessary-condition": "warn",
  "@typescript-eslint/switch-exhaustiveness-check": "error",
  "@typescript-eslint/no-mixed-enums": "error",
  "@typescript-eslint/no-unsafe-function-type": "error",
  "@typescript-eslint/no-wrapper-object-types": "error",
  "@typescript-eslint/no-unused-vars": "error",
  "@typescript-eslint/no-use-before-define": "error",
  "@typescript-eslint/no-shadow": "error",
  "@typescript-eslint/no-this-alias": "error",
  "@typescript-eslint/no-loop-func": "error",
  "@typescript-eslint/no-var-requires": "error",
  "@typescript-eslint/no-require-imports": "error",
  "@typescript-eslint/prefer-promise-reject-errors": "error",
  "@typescript-eslint/promise-function-async": "error",
  "@typescript-eslint/no-unused-expressions": "error",
  "@typescript-eslint/no-unsafe-type-assertion": "warn",
  "@typescript-eslint/adjacent-overload-signatures": "warn",
  "@typescript-eslint/array-type": "warn",
  "@typescript-eslint/ban-ts-comment": "warn",
  "@typescript-eslint/ban-tslint-comment": "warn",
  "@typescript-eslint/class-literal-property-style": "warn",
  "@typescript-eslint/class-methods-use-this": "warn",
  "@typescript-eslint/consistent-generic-constructors": "warn",
  "@typescript-eslint/consistent-indexed-object-style": "warn",
  "@typescript-eslint/consistent-return": "warn",
  "@typescript-eslint/consistent-type-assertions": "warn",
  "@typescript-eslint/consistent-type-definitions": "warn",
  "@typescript-eslint/consistent-type-exports": "warn",
  "@typescript-eslint/consistent-type-imports": "warn",
  "@typescript-eslint/default-param-last": "warn",
  "@typescript-eslint/dot-notation": "warn",
  "@typescript-eslint/explicit-function-return-type": "warn",
  "@typescript-eslint/explicit-member-accessibility": "warn",
  "@typescript-eslint/explicit-module-boundary-types": "warn",
  "@typescript-eslint/init-declarations": "warn",
  "@typescript-eslint/max-params": "warn",
  "@typescript-eslint/member-ordering": "warn",
  "@typescript-eslint/method-signature-style": "warn",
  "@typescript-eslint/naming-convention": "warn",
  "@typescript-eslint/no-array-constructor": "warn",
  "@typescript-eslint/no-confusing-non-null-assertion": "warn",
  "@typescript-eslint/no-confusing-void-expression": "warn",
  "@typescript-eslint/no-deprecated": "warn",
  "@typescript-eslint/no-duplicate-type-constituents": "warn",
  "@typescript-eslint/no-dynamic-delete": "warn",
  "@typescript-eslint/no-empty-function": "warn",
  "@typescript-eslint/no-empty-interface": "warn",
  "@typescript-eslint/no-empty-object-type": "warn",
  "@typescript-eslint/no-extraneous-class": "warn",
  "@typescript-eslint/no-import-type-side-effects": "warn",
  "@typescript-eslint/no-inferrable-types": "warn",
  "@typescript-eslint/no-invalid-this": "warn",
  "@typescript-eslint/no-magic-numbers": "warn",
  "@typescript-eslint/no-meaningless-void-operator": "warn",
  "@typescript-eslint/no-namespace": "warn",
  "@typescript-eslint/no-redundant-type-constituents": "warn",
  "@typescript-eslint/no-restricted-imports": "warn",
  "@typescript-eslint/no-restricted-types": "warn",
  "@typescript-eslint/no-type-alias": "warn",
  "@typescript-eslint/no-unnecessary-boolean-literal-compare": "warn",
  "@typescript-eslint/no-unnecessary-parameter-property-assignment": "warn",
  "@typescript-eslint/no-unnecessary-qualifier": "warn",
  "@typescript-eslint/no-unnecessary-template-expression": "warn",
  "@typescript-eslint/no-unnecessary-type-arguments": "warn",
  "@typescript-eslint/no-unnecessary-type-constraint": "warn",
  "@typescript-eslint/no-unnecessary-type-conversion": "warn",
  "@typescript-eslint/no-unnecessary-type-parameters": "warn",
  "@typescript-eslint/no-unused-private-class-members": "warn",
  "@typescript-eslint/no-useless-constructor": "warn",
  "@typescript-eslint/no-useless-default-assignment": "warn",
  "@typescript-eslint/no-useless-empty-export": "warn",
  "@typescript-eslint/non-nullable-type-assertion-style": "warn",
  "@typescript-eslint/parameter-properties": "warn",
  "@typescript-eslint/prefer-as-const": "warn",
  "@typescript-eslint/prefer-destructuring": "warn",
  "@typescript-eslint/prefer-enum-initializers": "warn",
  "@typescript-eslint/prefer-find": "warn",
  "@typescript-eslint/prefer-for-of": "warn",
  "@typescript-eslint/prefer-function-type": "warn",
  "@typescript-eslint/prefer-includes": "warn",
  "@typescript-eslint/prefer-literal-enum-member": "warn",
  "@typescript-eslint/prefer-namespace-keyword": "warn",
  "@typescript-eslint/prefer-nullish-coalescing": "warn",
  "@typescript-eslint/prefer-optional-chain": "warn",
  "@typescript-eslint/prefer-readonly": "warn",
  "@typescript-eslint/prefer-readonly-parameter-types": "warn",
  "@typescript-eslint/prefer-reduce-type-parameter": "warn",
  "@typescript-eslint/prefer-regexp-exec": "warn",
  "@typescript-eslint/prefer-return-this-type": "warn",
  "@typescript-eslint/prefer-string-starts-ends-with": "warn",
  "@typescript-eslint/prefer-ts-expect-error": "warn",
  "@typescript-eslint/related-getter-setter-pairs": "warn",
  "@typescript-eslint/require-await": "warn",
  "@typescript-eslint/sort-type-constituents": "warn",
  "@typescript-eslint/strict-void-return": "warn",
  "@typescript-eslint/triple-slash-reference": "warn",
  "@typescript-eslint/typedef": "warn",
  "@typescript-eslint/unified-signatures": "warn"
};
const sonarJSRules = {
  "sonarjs/no-hardcoded-secrets": "error",
  "sonarjs/no-hardcoded-passwords": "error",
  "sonarjs/no-hardcoded-ip": "error",
  "sonarjs/insecure-jwt-token": "error",
  "sonarjs/insecure-cookie": "error",
  "sonarjs/cookie-no-httponly": "error",
  "sonarjs/csrf": "error",
  "sonarjs/cors": "error",
  "sonarjs/encryption": "error",
  "sonarjs/no-weak-cipher": "error",
  "sonarjs/no-weak-keys": "error",
  "sonarjs/weak-ssl": "error",
  "sonarjs/unverified-certificate": "error",
  "sonarjs/unverified-hostname": "error",
  "sonarjs/xml-parser-xxe": "error",
  "sonarjs/sql-queries": "error",
  "sonarjs/os-command": "error",
  "sonarjs/no-os-command-from-path": "error",
  "sonarjs/code-eval": "error",
  "sonarjs/disabled-auto-escaping": "error",
  "sonarjs/no-angular-bypass-sanitization": "error",
  "sonarjs/no-vue-bypass-sanitization": "error",
  "sonarjs/dynamically-constructed-templates": "error",
  "sonarjs/publicly-writable-directories": "error",
  "sonarjs/no-unsafe-unzip": "error",
  "sonarjs/confidential-information-logging": "error",
  "sonarjs/hardcoded-secret-signatures": "error",
  "sonarjs/review-blockchain-mnemonic": "error",
  "sonarjs/pseudo-random": "error",
  "sonarjs/hashing": "error",
  "sonarjs/aws-iam-privilege-escalation": "error",
  "sonarjs/aws-iam-all-privileges": "error",
  "sonarjs/aws-s3-bucket-public-access": "error",
  "sonarjs/no-clear-text-protocols": "error",
  "sonarjs/no-use-of-empty-return-value": "error",
  "sonarjs/null-dereference": "error",
  "sonarjs/no-identical-conditions": "error",
  "sonarjs/no-identical-expressions": "error",
  "sonarjs/no-all-duplicated-branches": "error",
  "sonarjs/no-collection-size-mischeck": "error",
  "sonarjs/no-empty-collection": "error",
  "sonarjs/no-invariant-returns": "error",
  "sonarjs/non-existent-operator": "error",
  "sonarjs/updated-const-var": "error",
  "sonarjs/for-loop-increment-sign": "error",
  "sonarjs/no-equals-in-for-termination": "error",
  "sonarjs/operation-returning-nan": "error",
  "sonarjs/no-invalid-regexp": "error",
  "sonarjs/no-misleading-array-reverse": "error",
  "sonarjs/no-fallthrough": "error",
  "sonarjs/no-literal-call": "error",
  "sonarjs/no-reference-error": "error",
  "sonarjs/no-extra-arguments": "error",
  "sonarjs/arguments-order": "error",
  "sonarjs/argument-type": "error",
  "sonarjs/in-operator-type-error": "error",
  "sonarjs/no-for-in-iterable": "error",
  "sonarjs/no-async-constructor": "error",
  "sonarjs/no-hook-setter-in-body": "error",
  "sonarjs/no-uniq-key": "error",
  "sonarjs/no-dead-store": "error",
  "sonarjs/generator-without-yield": "error",
  "sonarjs/no-incomplete-assertions": "error",
  "sonarjs/no-exclusive-tests": "error",
  "sonarjs/cognitive-complexity": ["warn", 15],
  "sonarjs/no-duplicate-string": "warn",
  "sonarjs/no-duplicated-branches": "warn",
  "sonarjs/anchor-precedence": "warn",
  "sonarjs/arguments-usage": "warn",
  "sonarjs/array-callback-without-return": "warn",
  "sonarjs/array-constructor": "warn",
  "sonarjs/arrow-function-convention": "off",
  "sonarjs/assertions-in-tests": "warn",
  "sonarjs/aws-apigateway-public-api": "warn",
  "sonarjs/aws-ec2-rds-dms-public": "warn",
  "sonarjs/aws-ec2-unencrypted-ebs-volume": "warn",
  "sonarjs/aws-efs-unencrypted": "warn",
  "sonarjs/aws-iam-all-resources-accessible": "warn",
  "sonarjs/aws-iam-public-access": "warn",
  "sonarjs/aws-opensearchservice-domain": "warn",
  "sonarjs/aws-rds-unencrypted-databases": "warn",
  "sonarjs/aws-restricted-ip-admin-access": "warn",
  "sonarjs/aws-s3-bucket-granted-access": "warn",
  "sonarjs/aws-s3-bucket-insecure-http": "warn",
  "sonarjs/aws-s3-bucket-server-encryption": "warn",
  "sonarjs/aws-s3-bucket-versioning": "warn",
  "sonarjs/aws-sagemaker-unencrypted-notebook": "warn",
  "sonarjs/aws-sns-unencrypted-topics": "warn",
  "sonarjs/aws-sqs-unencrypted-queue": "warn",
  "sonarjs/bitwise-operators": "warn",
  "sonarjs/block-scoped-var": "warn",
  "sonarjs/bool-param-default": "warn",
  "sonarjs/call-argument-line": "warn",
  "sonarjs/certificate-transparency": "warn",
  "sonarjs/chai-determinate-assertion": "warn",
  "sonarjs/class-name": "warn",
  "sonarjs/class-prototype": "warn",
  "sonarjs/comma-or-logical-or-case": "warn",
  "sonarjs/comment-regex": "warn",
  "sonarjs/concise-regex": "warn",
  "sonarjs/conditional-indentation": "warn",
  "sonarjs/constructor-for-side-effects": "warn",
  "sonarjs/content-length": "warn",
  "sonarjs/content-security-policy": "warn",
  "sonarjs/cookies": "warn",
  "sonarjs/cyclomatic-complexity": "off",
  "sonarjs/declarations-in-global-scope": "off",
  "sonarjs/deprecation": "warn",
  "sonarjs/destructuring-assignment-syntax": "warn",
  "sonarjs/different-types-comparison": "error",
  "sonarjs/disabled-resource-integrity": "warn",
  "sonarjs/disabled-timeout": "warn",
  "sonarjs/dns-prefetching": "warn",
  "sonarjs/duplicates-in-character-class": "warn",
  "sonarjs/elseif-without-else": "warn",
  "sonarjs/empty-string-repetition": "warn",
  "sonarjs/encryption-secure-mode": "warn",
  "sonarjs/existing-groups": "warn",
  "sonarjs/expression-complexity": "warn",
  "sonarjs/file-header": "off",
  "sonarjs/file-name-differ-from-class": "off",
  "sonarjs/file-permissions": "warn",
  "sonarjs/file-uploads": "warn",
  "sonarjs/fixme-tag": "warn",
  "sonarjs/for-in": "warn",
  "sonarjs/frame-ancestors": "warn",
  "sonarjs/function-inside-loop": "warn",
  "sonarjs/function-name": "warn",
  "sonarjs/function-return-type": "warn",
  "sonarjs/future-reserved-words": "warn",
  "sonarjs/hidden-files": "warn",
  "sonarjs/inconsistent-function-call": "warn",
  "sonarjs/index-of-compare-to-positive-number": "warn",
  "sonarjs/inverted-assertion-arguments": "warn",
  "sonarjs/jsx-no-leaked-render": "warn",
  "sonarjs/label-position": "warn",
  "sonarjs/link-with-target-blank": "warn",
  "sonarjs/max-lines": "warn",
  "sonarjs/max-lines-per-function": "warn",
  "sonarjs/max-switch-cases": "warn",
  "sonarjs/max-union-size": "off",
  "sonarjs/misplaced-loop-counter": "warn",
  "sonarjs/nested-control-flow": "warn",
  "sonarjs/new-operator-misuse": "warn",
  "sonarjs/no-alphabetical-sort": "warn",
  "sonarjs/no-array-delete": "warn",
  "sonarjs/no-associative-arrays": "warn",
  "sonarjs/no-built-in-override": "warn",
  "sonarjs/no-case-label-in-switch": "warn",
  "sonarjs/no-code-after-done": "warn",
  "sonarjs/no-collapsible-if": "warn",
  "sonarjs/no-commented-code": "warn",
  "sonarjs/no-control-regex": "warn",
  "sonarjs/no-delete-var": "warn",
  "sonarjs/no-duplicate-in-composite": "warn",
  "sonarjs/no-element-overwrite": "warn",
  "sonarjs/no-empty-after-reluctant": "warn",
  "sonarjs/no-empty-alternatives": "warn",
  "sonarjs/no-empty-character-class": "warn",
  "sonarjs/no-empty-group": "warn",
  "sonarjs/no-empty-test-file": "warn",
  "sonarjs/no-function-declaration-in-block": "warn",
  "sonarjs/no-global-this": "warn",
  "sonarjs/no-globals-shadowing": "warn",
  "sonarjs/no-gratuitous-expressions": "warn",
  "sonarjs/no-identical-functions": "warn",
  "sonarjs/no-ignored-exceptions": "warn",
  "sonarjs/no-ignored-return": "warn",
  "sonarjs/no-implicit-dependencies": "warn",
  "sonarjs/no-implicit-global": "warn",
  "sonarjs/no-in-misuse": "warn",
  "sonarjs/no-inconsistent-returns": "warn",
  "sonarjs/no-incorrect-string-concat": "warn",
  "sonarjs/no-internal-api-use": "warn",
  "sonarjs/no-intrusive-permissions": "warn",
  "sonarjs/no-inverted-boolean-check": "warn",
  "sonarjs/no-ip-forward": "warn",
  "sonarjs/no-labels": "warn",
  "sonarjs/no-mime-sniff": "warn",
  "sonarjs/no-misleading-character-class": "warn",
  "sonarjs/no-mixed-content": "warn",
  "sonarjs/no-nested-assignment": "warn",
  "sonarjs/no-nested-conditional": "warn",
  "sonarjs/no-nested-functions": "warn",
  "sonarjs/no-nested-incdec": "warn",
  "sonarjs/no-nested-switch": "warn",
  "sonarjs/no-nested-template-literals": "warn",
  "sonarjs/no-parameter-reassignment": "warn",
  "sonarjs/no-primitive-wrappers": "warn",
  "sonarjs/no-redundant-assignments": "warn",
  "sonarjs/no-redundant-boolean": "warn",
  "sonarjs/no-redundant-jump": "warn",
  "sonarjs/no-redundant-optional": "warn",
  "sonarjs/no-redundant-parentheses": "warn",
  "sonarjs/no-referrer-policy": "warn",
  "sonarjs/no-regex-spaces": "warn",
  "sonarjs/no-require-or-define": "warn",
  "sonarjs/no-return-type-any": "warn",
  "sonarjs/no-same-argument-assert": "warn",
  "sonarjs/no-same-line-conditional": "warn",
  "sonarjs/no-selector-parameter": "warn",
  "sonarjs/no-session-cookies-on-static-assets": "warn",
  "sonarjs/no-skipped-tests": "warn",
  "sonarjs/no-small-switch": "warn",
  "sonarjs/no-sonar-comments": "warn",
  "sonarjs/no-tab": "warn",
  "sonarjs/no-table-as-layout": "warn",
  "sonarjs/no-try-promise": "warn",
  "sonarjs/no-undefined-argument": "warn",
  "sonarjs/no-undefined-assignment": "warn",
  "sonarjs/no-unenclosed-multiline-block": "warn",
  "sonarjs/no-unthrown-error": "warn",
  "sonarjs/no-unused-collection": "warn",
  "sonarjs/no-unused-function-argument": "warn",
  "sonarjs/no-unused-vars": "warn",
  "sonarjs/no-useless-catch": "warn",
  "sonarjs/no-useless-increment": "warn",
  "sonarjs/no-useless-intersection": "warn",
  "sonarjs/no-useless-react-setstate": "warn",
  "sonarjs/no-variable-usage-before-declaration": "warn",
  "sonarjs/no-wildcard-import": "off",
  "sonarjs/non-number-in-arithmetic-expression": "warn",
  "sonarjs/object-alt-content": "warn",
  "sonarjs/post-message": "warn",
  "sonarjs/prefer-default-last": "warn",
  "sonarjs/prefer-immediate-return": "warn",
  "sonarjs/prefer-object-literal": "warn",
  "sonarjs/prefer-promise-shorthand": "warn",
  "sonarjs/prefer-read-only-props": "off",
  "sonarjs/prefer-regexp-exec": "warn",
  "sonarjs/prefer-single-boolean-return": "warn",
  "sonarjs/prefer-type-guard": "warn",
  "sonarjs/prefer-while": "warn",
  "sonarjs/process-argv": "warn",
  "sonarjs/production-debug": "warn",
  "sonarjs/public-static-readonly": "warn",
  "sonarjs/reduce-initial-value": "warn",
  "sonarjs/redundant-type-aliases": "warn",
  "sonarjs/regex-complexity": "warn",
  "sonarjs/regular-expr": "warn",
  "sonarjs/session-regeneration": "warn",
  "sonarjs/shorthand-property-grouping": "warn",
  "sonarjs/single-char-in-character-classes": "warn",
  "sonarjs/single-character-alternation": "warn",
  "sonarjs/slow-regex": "warn",
  "sonarjs/sockets": "warn",
  "sonarjs/stable-tests": "warn",
  "sonarjs/standard-input": "warn",
  "sonarjs/stateful-regex": "warn",
  "sonarjs/strict-transport-security": "warn",
  "sonarjs/strings-comparison": "warn",
  "sonarjs/table-header": "warn",
  "sonarjs/table-header-reference": "warn",
  "sonarjs/test-check-exception": "warn",
  "sonarjs/todo-tag": "warn",
  "sonarjs/too-many-break-or-continue-in-loop": "warn",
  "sonarjs/unicode-aware-regex": "warn",
  "sonarjs/unused-import": "warn",
  "sonarjs/unused-named-groups": "warn",
  "sonarjs/updated-loop-counter": "warn",
  "sonarjs/use-type-alias": "warn",
  "sonarjs/useless-string-operation": "warn",
  "sonarjs/values-not-convertible-to-numbers": "warn",
  "sonarjs/variable-name": "warn",
  "sonarjs/void-use": "warn",
  "sonarjs/web-sql-database": "warn",
  "sonarjs/x-powered-by": "warn",
  "sonarjs/xpath": "warn"
};
export default defineConfig([
  // ========================
  // BASE (shared)
  // ========================
  {
    ignores: ["dist", "node_modules"]
  },

  // ========================
  // JAVASCRIPT CONFIG
  // ========================
  {
    files: ["**/*.js", "**/*.mjs", "**/*.cjs"],

    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        ...globals.node
      }
    },

    plugins: {
      import: importPlugin,
      "unused-imports": unusedImports,
      sonarjs,
      jsdoc
    },
    extends: [
      tseslint.configs.eslintRecommended,
      importPlugin.flatConfigs.recommended,
      eslintConfigPrettier // MUST be the last item
    ],

    rules: {
      // ---- Structure (keep yours, slightly relaxed)
      complexity: ["error", { max: 8 }],
      "max-depth": ["error", 3],
      "max-params": ["error", 4],

      // ---- Clean code
      "unused-imports/no-unused-imports": "error",
      "unused-imports/no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],

      // ---- Imports
      "import/order": [
        "error",
        {
          groups: ["builtin", "external", "internal"],
          "newlines-between": "always",
          alphabetize: { order: "asc", caseInsensitive: true }
        }
      ],
      "import/no-cycle": "error",
      "import/no-unresolved": "off",
      "import-x/no-unresolved": "off",

      // ---- Bug prevention
      "no-console": ["warn", { allow: ["warn", "error"] }],
      "no-debugger": "error",
      eqeqeq: ["error", "always", { null: "ignore" }],
      curly: ["error", "all"],

      // ---- Maintainability
      ...sonarJSRules,
      ...jsdocRules
    }
  },

  // ========================
  // TYPESCRIPT CONFIG
  // ========================
  {
    files: ["**/*.ts", "**/*.tsx"],

    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        project: "./tsconfig.json"
      },
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        ...globals.node
      }
    },

    plugins: {
      "@typescript-eslint": tseslint.plugin,
      import: importPlugin,
      "unused-imports": unusedImports,
      sonarjs
    },
    extends: [
      tseslint.configs.eslintRecommended,
      importPlugin.flatConfigs.recommended,
      eslintConfigPrettier // MUST be the last item
    ],

    rules: {
      // ---- Structure
      complexity: ["error", { max: 15 }],
      "max-depth": ["error", 3],
      "max-params": ["error", 4],

      // ---- TS critical (main difference)
      ...typescriptEslintRules,

      // ---- Clean
      "unused-imports/no-unused-imports": "error",
      "unused-imports/no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],

      // ---- Imports
      "import/order": [
        "error",
        {
          groups: ["builtin", "external", "internal"],
          "newlines-between": "always",
          alphabetize: { order: "asc", caseInsensitive: true }
        }
      ],
      "import/no-cycle": "error",
      "import/no-unresolved": "off",
      "import-x/no-unresolved": "off",

      // ---- Bug prevention
      "no-console": ["warn", { allow: ["warn", "error"] }],
      "no-debugger": "error",
      eqeqeq: ["error", "always", { null: "ignore" }],
      curly: ["error", "all"],

      // ---- Code quality
      ...sonarJSRules
    }
  },

  // ========================
  // TESTS OVERRIDE
  // ========================
  {
    files: ["**/*.test.ts", "**/*.test.js"],
    extends: [
      tseslint.configs.eslintRecommended,
      importPlugin.flatConfigs.recommended,
      eslintConfigPrettier // MUST be the last item
    ],
    rules: {
      "sonarjs/cognitive-complexity": "off",
      "@typescript-eslint/no-explicit-any": "off"
    }
  }
]);
